export default [
    {
        id: '1',
        title: 'Inception',
        releaseYear: 2010,
        genre: 'Science Fiction',
        rating: 8.8,
        img: './inception.jpg',
    },
    {
        id: '2',
        title: 'The Dark Knight',
        releaseYear: 2008,
        genre: 'Action',
        rating: 9.0,
        img: './theDarkKnight.jpeg',
    },
    {
        id: '3',
        title: 'Interstellar',
        releaseYear: 2014,
        genre: 'Science Fiction',
        rating: 8.6,
        img: './intersteller.jpeg',
    },
    {
        id: '4',
        title: 'Avengers: Endgame',
        releaseYear: 2019,
        genre: 'Action',
        rating: 8.4,
        img: '/endgame.jpeg',
    },
    {
        id: '5',
        title: 'Black Panther',
        releaseYear: 2018,
        genre: 'Action',
        rating: 7.3,
        img: '/blackpanther.jpeg',
    },
    {
        id: '6',
        title: 'Joker',
        releaseYear: 2019,
        genre: 'Drama',
        rating: 8.4,
        img: 'joker.jpg',
    },
    {
        id: '7',
        title: 'Wonder Woman',
        releaseYear: 2017,
        genre: 'Action',
        rating: 7.4,
        img: 'wonderWoman.jpeg',
    },
    {
        id: '8',
        title: 'Spider-Man: Into the Spider-Verse',
        releaseYear: 2018,
        genre: 'Animation',
        rating: 8.4,
        img: '/spiderman.jpeg',
    },
    {
        id: '9',
        title: 'The Lion King',
        releaseYear: 2019,
        genre: 'Animation',
        rating: 6.9,
        img: '/lionking.jpeg',
    },
];
